ci 수정 후 재시도 - runner

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -13,12 +13,9 @@ jobs:
       uses: actions/checkout@v3
 
     - name: Set up Test MySQL
-      uses: mirromutth/mysql-action@v1.1
-      with:
-        host port: 3307
-        container port: 3306
-        mysql database: 'testdb'
-        mysql root password: testPw1234!
+      run: |
+        docker compose -f ~/ci-docker-compose.yml up -d
+      shell: bash
         
     - name: Make test application.yml
       run: |
@@ -46,14 +43,19 @@ jobs:
     - name: Running Test Code
       run: ./gradlew --info test
 
-    - name: Publish Unit Test Results
-      uses: EnricoMi/publish-unit-test-result-action@v1
-      if: ${{ always() }}
-      with:
-        files: build/test-results/**/*.xml
+#    - name: Publish Unit Test Results
+#      uses: EnricoMi/publish-unit-test-result-action@v1
+#      if: ${{ always() }}
+#      with:
+#        files: build/test-results/**/*.xml
+#
+#    - name: Publish Test Report
+#      uses: mikepenz/action-junit-report@v3
+#      if: success() || failure() # always run even if the previous step fails
+#      with:
+#        report_paths: '**/build/test-results/test/TEST-*.xml'
 
-    - name: Publish Test Report
-      uses: mikepenz/action-junit-report@v3
-      if: success() || failure() # always run even if the previous step fails
-      with:
-        report_paths: '**/build/test-results/test/TEST-*.xml'
+    - name: Clear Test MySQL
+      run: |
+        docker compose -f ~/ci-docker-compose.yml down
+      shell: bash
