test yml로 시도

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -23,6 +23,14 @@ jobs:
       with:
         java-version: '17'
         distribution: 'temurin'
+
+    - name: Set up Test MySQL DB
+      uses: mirromutth/mysql-action@v1.1
+      with:
+        host port: 3306
+        container port: 3306
+        mysql database: 'coduo'
+        mysql root password: testPw1234!
         
     - name: make application-database.yml
       run: |
@@ -30,10 +38,11 @@ jobs:
         cd ./src/main/resources
 
         # application-database.yml 파일 생성
-        touch ./application-database.yml
+        rm -f ./application.yml
+        touch ./application.yml
 
-        # GitHub-Actions 에서 설정한 값을 application-database.yaml 파일에 쓰기
-        echo ${{secrets.DATABASEYML}} | base64 --decode > ./application-database.yml
+        # GitHub-Actions 에서 설정한 값을 application.yaml 파일에 쓰기
+        echo ${{secrets.TESTYML}} | base64 --decode > ./application.yml
       shell: bash
 
     - name: Gradle Caching
@@ -51,3 +60,19 @@ jobs:
 
     - name: Build With Gradle
       run: ./gradlew build -x test
+
+      # build Test
+    - name: 테스트 코드 실행
+      run: ./gradlew --info test
+
+    - name: Publish Unit Test Results
+      uses: EnricoMi/publish-unit-test-result-action@v1
+      if: ${{ always() }}
+      with:
+        files: build/test-results/**/*.xml
+
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v3
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: '**/build/test-results/test/TEST-*.xml'
